import { relations } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgEnum,
  pgTable,
  real,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

/* ═══════════════════════ Better Auth identity ══════════════════════ */

/**
 * Generated by `@better-auth/cli generate` — do not hand-edit the columns.
 *
 * These live in this file rather than a separate module because drizzle-kit
 * resolves the schema through CJS `require`, which cannot follow the `.js`
 * extension our ESM sources use. One file, no cross-import, no resolution
 * problem in either toolchain.
 */
export const user = pgTable('user', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull().unique(),
  emailVerified: boolean('email_verified').default(false).notNull(),
  image: text('image'),
  createdAt: timestamp('created_at').defaultNow().notNull(),
  updatedAt: timestamp('updated_at')
    .defaultNow()
    .$onUpdate(() => new Date())
    .notNull(),
  role: text('role').default('compliance_officer'),
});

export const session = pgTable(
  'session',
  {
    id: text('id').primaryKey(),
    expiresAt: timestamp('expires_at').notNull(),
    token: text('token').notNull().unique(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
  },
  (table) => [index('session_userId_idx').on(table.userId)],
);

export const account = pgTable(
  'account',
  {
    id: text('id').primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at'),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at'),
    scope: text('scope'),
    password: text('password'),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('account_userId_idx').on(table.userId)],
);

export const verification = pgTable(
  'verification',
  {
    id: text('id').primaryKey(),
    identifier: text('identifier').notNull(),
    value: text('value').notNull(),
    expiresAt: timestamp('expires_at').notNull(),
    createdAt: timestamp('created_at').defaultNow().notNull(),
    updatedAt: timestamp('updated_at')
      .defaultNow()
      .$onUpdate(() => new Date())
      .notNull(),
  },
  (table) => [index('verification_identifier_idx').on(table.identifier)],
);

export const userRelations = relations(user, ({ many }) => ({
  sessions: many(session),
  accounts: many(account),
  decisions: many(decisions),
}));

export const sessionRelations = relations(session, ({ one }) => ({
  user: one(user, { fields: [session.userId], references: [user.id] }),
}));

export const accountRelations = relations(account, ({ one }) => ({
  user: one(user, { fields: [account.userId], references: [user.id] }),
}));

/* ────────────────────────────── enums ────────────────────────────── */

export const employmentTypeEnum = pgEnum('employment_type', [
  'salaried',
  'self_employed',
  'business_owner',
  'freelancer',
  'student',
  'unemployed',
  'retired',
]);

export const incomeSourceEnum = pgEnum('income_source', [
  'salary',
  'business',
  'freelance',
  'remittance',
  'agriculture',
  'pension',
  'other',
]);

export const residenceTypeEnum = pgEnum('residence_type', ['owned', 'rented', 'family']);

export const accountPurposeEnum = pgEnum('account_purpose', [
  'personal_use',
  'receive_business_payments',
  'receive_remittance',
  'savings',
  'merchant_collection',
]);

export const counterpartiesEnum = pgEnum('counterparties', ['domestic', 'international']);

export const riskLevelEnum = pgEnum('risk_level', ['low', 'medium', 'high']);

export const severityEnum = pgEnum('severity', ['low', 'medium', 'high']);

export const caseStatusEnum = pgEnum('case_status', [
  'pending',
  'edd_queue',
  'approved',
  'declined',
  'escalated',
]);

export const decisionActionEnum = pgEnum('decision_action', ['approve', 'reject', 'escalate']);

export const clusterKindEnum = pgEnum('cluster_kind', ['device_reuse', 'agent_point']);

/* ─────────────────────────── applications ────────────────────────── */

/** What the applicant declared. */
export const applications = pgTable('applications', {
  id: uuid('id').primaryKey().defaultRandom(),
  reference: text('reference').notNull().unique(), // PK-4471

  // identity
  cnic: text('cnic').notNull(), // 00000-0000000-0
  fullName: text('full_name').notNull(),
  dob: text('dob').notNull(), // ISO date
  cnicExpiry: text('cnic_expiry').notNull(), // ISO date

  // address
  city: text('city').notNull(),
  area: text('area').notNull(),
  residenceType: residenceTypeEnum('residence_type').notNull(),
  yearsAtAddress: real('years_at_address').notNull(),

  // work & income
  employmentType: employmentTypeEnum('employment_type').notNull(),
  employerName: text('employer_name'),
  incomeSource: incomeSourceEnum('income_source').notNull(),
  declaredIncomePkr: numeric('declared_income_pkr', { precision: 14, scale: 2 }).notNull(),

  // account purpose & expected activity
  accountPurpose: accountPurposeEnum('account_purpose').notNull(),
  expectedVolumePkr: numeric('expected_volume_pkr', { precision: 14, scale: 2 }).notNull(),
  expectedTxnCount: integer('expected_txn_count').notNull(),
  counterparties: counterpartiesEnum('counterparties').notNull(),
  isPep: boolean('is_pep').notNull().default(false),
  existingBankRelationship: boolean('existing_bank_relationship').notNull().default(false),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * What the system observed, as opposed to what the applicant said.
 * Kept separate on purpose — it makes the provenance of every signal obvious.
 */
export const applicationMeta = pgTable('application_meta', {
  id: uuid('id').primaryKey().defaultRandom(),
  applicationId: uuid('application_id')
    .notNull()
    .references(() => applications.id, { onDelete: 'cascade' }),

  deviceFingerprint: text('device_fingerprint').notNull(),
  agentPointId: text('agent_point_id').notNull(), // RWP-114
  sessionCity: text('session_city'),
  sessionLat: real('session_lat'),
  sessionLng: real('session_lng'),
  secondsPerStep: jsonb('seconds_per_step').$type<number[]>(),

  submittedAt: timestamp('submitted_at', { withTimezone: true }).notNull().defaultNow(),
});

/* ───────────────────────────── signals ───────────────────────────── */

/** Output of the signal engine. One row per tripped signal. */
export const signals = pgTable('signals', {
  id: uuid('id').primaryKey().defaultRandom(),
  applicationId: uuid('application_id')
    .notNull()
    .references(() => applications.id, { onDelete: 'cascade' }),

  name: text('name').notNull(), // income_volume_mismatch
  label: text('label').notNull(), // Income–volume mismatch
  severity: severityEnum('severity').notNull(),
  evidence: text('evidence').notNull(), // real figures, always
  fields: jsonb('fields').$type<string[]>().notNull(),
  clusterRef: text('cluster_ref'),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/* ──────────────────────────── clusters ───────────────────────────── */

/** Cross-application patterns. Only visible in aggregate. */
export const clusters = pgTable('clusters', {
  id: uuid('id').primaryKey().defaultRandom(),
  ref: text('ref').notNull().unique(), // CLU-881
  kind: clusterKindEnum('kind').notNull(),

  agentPointId: text('agent_point_id'),
  deviceFingerprint: text('device_fingerprint'),
  applicationIds: jsonb('application_ids').$type<string[]>().notNull(),
  summary: text('summary').notNull(), // rendered on the dashboard banner

  detectedAt: timestamp('detected_at', { withTimezone: true }).notNull().defaultNow(),
});

/* ────────────────────────── risk profiles ────────────────────────── */

export type ContributingSignal = {
  name: string;
  label: string;
  weight: number;
  evidence: string;
};

/** Output of the AI risk agent. */
export const riskProfiles = pgTable('risk_profiles', {
  id: uuid('id').primaryKey().defaultRandom(),
  applicationId: uuid('application_id')
    .notNull()
    .references(() => applications.id, { onDelete: 'cascade' }),

  riskLevel: riskLevelEnum('risk_level').notNull(),
  confidence: real('confidence').notNull(),
  reasoning: text('reasoning').notNull(),
  contributingSignals: jsonb('contributing_signals').$type<ContributingSignal[]>().notNull(),
  recommendedAction: text('recommended_action').notNull(),

  model: text('model').notNull(),
  latencyMs: integer('latency_ms'),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/* ───────────────────────────── cases ─────────────────────────────── */

export const cases = pgTable('cases', {
  id: uuid('id').primaryKey().defaultRandom(),
  applicationId: uuid('application_id')
    .notNull()
    .references(() => applications.id, { onDelete: 'cascade' }),

  status: caseStatusEnum('status').notNull().default('pending'),
  assignedTo: text('assigned_to').references(() => user.id),

  queuedAt: timestamp('queued_at', { withTimezone: true }),
  resolvedAt: timestamp('resolved_at', { withTimezone: true }),

  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/* ──────────────────────────── officers ───────────────────────────── */

/*
 * Officers are Better Auth users — see the `user` table at the top of this file.
 *
 * There is deliberately no separate `officers` table: a second identity store
 * would drift from the session store, and then "who decided this" and "who is
 * signed in" could disagree — which is precisely the question an audit trail
 * exists to answer. `user.role` carries compliance_officer | senior_officer.
 */

/* ──────────────────────────── decisions ──────────────────────────── */

/**
 * The audit trail.
 *
 * risk/reasoning are stored as SNAPSHOTS, not foreign keys. A compliance audit
 * has to show what was known at decision time — recomputing on reopen would
 * make the trail worthless.
 */
export const decisions = pgTable('decisions', {
  id: uuid('id').primaryKey().defaultRandom(),
  caseId: uuid('case_id')
    .notNull()
    .references(() => cases.id, { onDelete: 'cascade' }),
  officerId: text('officer_id')
    .notNull()
    .references(() => user.id),

  action: decisionActionEnum('action').notNull(),
  justification: text('justification').notNull(),

  riskSnapshot: riskLevelEnum('risk_snapshot').notNull(),
  confidenceSnapshot: real('confidence_snapshot').notNull(),
  reasoningSnapshot: text('reasoning_snapshot').notNull(),
  signalsSnapshot: jsonb('signals_snapshot').$type<ContributingSignal[]>().notNull(),

  decidedAt: timestamp('decided_at', { withTimezone: true }).notNull().defaultNow(),
});

/* ──────────────────────────── relations ──────────────────────────── */

export const applicationsRelations = relations(applications, ({ one, many }) => ({
  meta: one(applicationMeta, {
    fields: [applications.id],
    references: [applicationMeta.applicationId],
  }),
  riskProfile: one(riskProfiles, {
    fields: [applications.id],
    references: [riskProfiles.applicationId],
  }),
  case: one(cases, {
    fields: [applications.id],
    references: [cases.applicationId],
  }),
  signals: many(signals),
}));

export const applicationMetaRelations = relations(applicationMeta, ({ one }) => ({
  application: one(applications, {
    fields: [applicationMeta.applicationId],
    references: [applications.id],
  }),
}));

export const signalsRelations = relations(signals, ({ one }) => ({
  application: one(applications, {
    fields: [signals.applicationId],
    references: [applications.id],
  }),
}));

export const riskProfilesRelations = relations(riskProfiles, ({ one }) => ({
  application: one(applications, {
    fields: [riskProfiles.applicationId],
    references: [applications.id],
  }),
}));

export const casesRelations = relations(cases, ({ one, many }) => ({
  application: one(applications, {
    fields: [cases.applicationId],
    references: [applications.id],
  }),
  assignee: one(user, {
    fields: [cases.assignedTo],
    references: [user.id],
  }),
  decisions: many(decisions),
}));

export const decisionsRelations = relations(decisions, ({ one }) => ({
  case: one(cases, {
    fields: [decisions.caseId],
    references: [cases.id],
  }),
  officer: one(user, {
    fields: [decisions.officerId],
    references: [user.id],
  }),
}));

/* ─────────────────────────── inferred types ──────────────────────── */

export type Application = typeof applications.$inferSelect;
export type NewApplication = typeof applications.$inferInsert;
export type ApplicationMeta = typeof applicationMeta.$inferSelect;
export type NewApplicationMeta = typeof applicationMeta.$inferInsert;
export type SignalRow = typeof signals.$inferSelect;
export type NewSignalRow = typeof signals.$inferInsert;
export type Cluster = typeof clusters.$inferSelect;
export type NewCluster = typeof clusters.$inferInsert;
export type RiskProfile = typeof riskProfiles.$inferSelect;
export type NewRiskProfile = typeof riskProfiles.$inferInsert;
export type Case = typeof cases.$inferSelect;
export type NewCase = typeof cases.$inferInsert;
export type Officer = typeof user.$inferSelect;
export type Decision = typeof decisions.$inferSelect;
export type NewDecision = typeof decisions.$inferInsert;
